# permissions for end users to view knitnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knitnet-viewer-role
rules:
- apiGroups:
  - operator.tkestack.io
  resources:
  - knitnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.tkestack.io
  resources:
  - knitnets/status
  verbs:
  - get
