# permissions for end users to edit knitnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knitnet-editor-role
rules:
- apiGroups:
  - operator.tkestack.io
  resources:
  - knitnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.tkestack.io
  resources:
  - knitnets/status
  verbs:
  - get
