
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.tkestack.io
  resources:
  - fabrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.tkestack.io
  resources:
  - fabrics/finalizers
  verbs:
  - update
- apiGroups:
  - operator.tkestack.io
  resources:
  - fabrics/status
  verbs:
  - get
  - patch
  - update
